# Capstone Project 4

##Smart Traffic Sign Recognition System

Scenario
A city is building a Smart Traffic Monitoring System to improve road safety.

Every intersection in the city will have cameras that detect traffic signs automatically.

The system must recognize different road signs such as:

Stop sign

Speed limit sign

Pedestrian crossing sign

The system will be used in autonomous vehicles and traffic monitoring cameras.

However, the engineers discovered two challenges:

1️⃣ First, the system must understand basic classification logic (learning from features).
2️⃣ Second, it must classify images of traffic signs captured by cameras.

To solve this, the engineering team decided to build the system in two stages.

Stage 1
Learning Basic Neural Networks (Perceptron)
Before building a full image model, the engineers want students to first implement a Perceptron-based neural network to understand how neural networks make decisions.

The perceptron will predict whether a traffic sign means "STOP" or "NOT STOP" using extracted features.

In [ ]:
import torch
import torch.nn as nn
import torch.optim as opt
import pandas as pd

In [ ]:
df=pd.DataFrame(pd.read_csv('DatasetCapstoneProject4.csv'))

In [ ]:
df.head()

,Sign_ID,Red_Color_Intensity,Circular_Shape,Text_Present,Edge_Count,Stop_Sign
0,1,0.90,0,1,8,1
1,2,0.20,1,0,4,0
2,3,0.85,0,1,7,1
3,4,0.30,1,0,5,0
4,5,0.88,0,1,8,1

In [ ]:
X=df.drop(['Sign_ID','Stop_Sign'],axis=1)

In [ ]:
X.head()

   Red_Color_Intensity  Circular_Shape  Text_Present  Edge_Count
0                 0.90               0             1           8
1                 0.20               1             0           4
2                 0.85               0             1           7
3                 0.30               1             0           5
4                 0.88               0             1           8

In [ ]:
y=df['Stop_Sign']

In [ ]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Stop_Sign, dtype: int64

# Creating the perceptron

In [ ]:
class Perceptron(nn.Module):

    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(X.shape[1], 1)  # it is automatically matches feature count no need to do manually

    def forward(self, x):
        return torch.sigmoid(self.linear(x))

In [ ]:
model=Perceptron()
learning_rate = 0.1

In [ ]:
for epoch in range(100):
  for i in range(len(X)):
        xi = torch.tensor(X.iloc[i].values, dtype=torch.float32)
        target = torch.tensor(y.iloc[i], dtype=torch.float32)
        output = model(xi)
        prediction = 1 if output >= 0.5 else 0
        error = target - prediction
        with torch.no_grad():
            model.linear.weight += learning_rate * error * xi
            model.linear.bias += learning_rate * error

if (epoch+1) % 10 == 0:
        print(f"Epoch {epoch+1} completed")

Epoch 100 completed

In [ ]:
test = torch.tensor([0.9,0.85,1,0], dtype=torch.float32)

result = model(test)

if result==1:
  print('Traffic sign is STOP')
else:
  print("Traffic sign is NOT STOP")

print("\nPrediction Probability:", result.item())
print("Predicted Class:", 1 if result>=0.5 else 0)

Traffic sign is NOT STOP

Prediction Probability: 0.2495463341474533
Predicted Class: 0