##Capstone Project 3

# Smart Marketing Prediction System (ML Pipeline Project)
Scenario
A fast-growing e-commerce company called ShopEasy is struggling with inefficient marketing campaigns.
Every day thousands of users visit their website. The marketing team spends a large amount of money showing ads, discounts, and promotional emails, but they don't know which customers are actually likely to buy something.
Currently:
Many customers browse but never purchase
Marketing money is wasted on the wrong users
The company wants to predict purchase probability
The data science team has been asked to build a machine learning system that predicts whether a customer will purchase a product during a session.
If the system predicts high probability of purchase, the system will:
show personalized product recommendations
offer targeted discounts
prioritize marketing campaigns
If the system predicts low probability, the company will avoid spending marketing resources.
However, the dataset contains both numerical and categorical features, so the data science team must design a complete ML pipeline.
Business Objective
Build a machine learning model that predicts whether a user will purchase (1) or not purchase (0) during a website session.
The model must be implemented using scikit-learn pipelines, including:
Encoding techniques
Feature preprocessing
Model training
Model selection
Hyperparameter tuning

In [32]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score,r2_score, classification_report

In [33]:
df=pd.read_excel('DatasetCapstoneProject3.xlsx')

In [34]:
df.head()

,CustomerID,Age,Gender,Device,Traffic_Source,Time_on_Website,Pages_Visited,Ad_Clicks,Previous_Purchases,Purchased
0,1,23,Male,Mobile,Social Media,5,3,1,0,0
1,2,35,Female,Desktop,Search Engine,12,8,3,2,1
2,3,29,Male,Tablet,Social Media,8,5,2,1,0
3,4,41,Female,Mobile,Email Campaign,15,10,4,3,1
4,5,22,Female,Desktop,Direct,4,2,0,0,0

In [35]:
df.columns = df.columns.str.strip()

In [36]:
df["Gender"] = df["Gender"].map({
    "Male":1,
    "Female":0
})

In [37]:
X=df.drop(['CustomerID','Purchased'],axis=1)

In [38]:
X.head()

,Age,Gender,Device,Traffic_Source,Time_on_Website,Pages_Visited,Ad_Clicks,Previous_Purchases
0,23,1,Mobile,Social Media,5,3,1,0
1,35,0,Desktop,Search Engine,12,8,3,2
2,29,1,Tablet,Social Media,8,5,2,1
3,41,0,Mobile,Email Campaign,15,10,4,3
4,22,0,Desktop,Direct,4,2,0,0

In [39]:
y=df['Purchased']

In [40]:
y.head()

0    0
1    1
2    0
3    1
4    0
Name: Purchased, dtype: int64

In [41]:
# Automatically dividing the data in numerical and categorical data by using select_dtypes method
numerical_cols = X.select_dtypes(include=["int64","float64"]).columns

categorical_cols = X.select_dtypes(include=["object"]).columns

In [42]:
print("Numerical:", numerical_cols)
print("Categorical:", categorical_cols)

Numerical: Index(['Age', 'Gender', 'Time_on_Website', 'Pages_Visited', 'Ad_Clicks',
       'Previous_Purchases'],
      dtype='object')
Categorical: Index(['Device', 'Traffic_Source'], dtype='object')

In [43]:
# applying scaler operation on columns using ColumnTransformer library
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_cols),
        ("cat", OneHotEncoder(), categorical_cols)
    ]
)

In [44]:
# using complete ML pipeline
model = Pipeline([
    ("preprocessing", preprocessor),
    ("classifier", LogisticRegression())
])

In [45]:
# splitting the data in training as testing parts
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['Age', 'Gender', 'Time_on_Website', 'Pages_Visited', 'Ad_Clicks',
       'Previous_Purchases'],
      dtype='object')),
                                                 ('cat', OneHotEncoder(),
                                                  Index(['Device', 'Traffic_Source'], dtype='object'))])),
                ('classifier', LogisticRegression())])

In [46]:
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         1

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

In [47]:
new_customer = pd.DataFrame({
    "Age":[30],
    "Gender":["1"],
    "Device":["Mobile"],
    "Traffic_Source":["Social Media"],
    "Time_on_Website":[7],
    "Pages_Visited":[5],
    "Ad_Clicks":[2],
    "Previous_Purchases":[1]
})

prediction = model.predict(new_customer)
probability = model.predict_proba(new_customer)

if prediction==0:
    print('Customer will not purchase')
else:
    print('Customer will purchase')

print("Prediction:", prediction)
print("Purchase Probability:", probability)

Customer will not purchase
Prediction: [0]
Purchase Probability: [[0.79674423 0.20325577]]

# Capstone Project 4

##Smart Traffic Sign Recognition System

Scenario
A city is building a Smart Traffic Monitoring System to improve road safety.

Every intersection in the city will have cameras that detect traffic signs automatically.

The system must recognize different road signs such as:

Stop sign

Speed limit sign

Pedestrian crossing sign

The system will be used in autonomous vehicles and traffic monitoring cameras.

However, the engineers discovered two challenges:

1️⃣ First, the system must understand basic classification logic (learning from features).
2️⃣ Second, it must classify images of traffic signs captured by cameras.

To solve this, the engineering team decided to build the system in two stages.

Stage 1
Learning Basic Neural Networks (Perceptron)
Before building a full image model, the engineers want students to first implement a Perceptron-based neural network to understand how neural networks make decisions.

The perceptron will predict whether a traffic sign means "STOP" or "NOT STOP" using extracted features.

In [ ]:
import torch
import torch.nn as nn
import torch.optim as opt
import pandas as pd

In [ ]:
df=pd.DataFrame(pd.read_csv('DatasetCapstoneProject4.csv'))

In [ ]:
df.head()

,Sign_ID,Red_Color_Intensity,Circular_Shape,Text_Present,Edge_Count,Stop_Sign
0,1,0.90,0,1,8,1
1,2,0.20,1,0,4,0
2,3,0.85,0,1,7,1
3,4,0.30,1,0,5,0
4,5,0.88,0,1,8,1

In [ ]:
X=df.drop(['Sign_ID','Stop_Sign'],axis=1)

In [ ]:
X.head()

   Red_Color_Intensity  Circular_Shape  Text_Present  Edge_Count
0                 0.90               0             1           8
1                 0.20               1             0           4
2                 0.85               0             1           7
3                 0.30               1             0           5
4                 0.88               0             1           8

In [ ]:
y=df['Stop_Sign']

In [ ]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Stop_Sign, dtype: int64

# Creating the perceptron

In [ ]:
class Perceptron(nn.Module):

    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(X.shape[1], 1)  # it is automatically matches feature count no need to do manually

    def forward(self, x):
        return torch.sigmoid(self.linear(x))

In [ ]:
model=Perceptron()
learning_rate = 0.1

In [ ]:
for epoch in range(100):
  for i in range(len(X)):
        xi = torch.tensor(X.iloc[i].values, dtype=torch.float32)
        target = torch.tensor(y.iloc[i], dtype=torch.float32)
        output = model(xi)
        prediction = 1 if output >= 0.5 else 0
        error = target - prediction
        with torch.no_grad():
            model.linear.weight += learning_rate * error * xi
            model.linear.bias += learning_rate * error

if (epoch+1) % 10 == 0:
        print(f"Epoch {epoch+1} completed")

Epoch 100 completed

In [ ]:
test = torch.tensor([0.9,0.85,1,0], dtype=torch.float32)

result = model(test)

if result==1:
  print('Traffic sign is STOP')
else:
  print("Traffic sign is NOT STOP")

print("\nPrediction Probability:", result.item())
print("Predicted Class:", 1 if result>=0.5 else 0)

Traffic sign is NOT STOP

Prediction Probability: 0.2495463341474533
Predicted Class: 0