# Capstone Project 3

## Smart Marketing Prediction System (ML Pipeline Project)

### Scenario
### A fast-growing e-commerce company called ShopEasy is struggling with inefficient marketing campaigns.

### Every day thousands of users visit their website. The marketing team spends a large amount of money showing ads, discounts, and promotional emails, but they don't know which customers are actually likely to buy something.

### Currently:

### Many customers browse but never purchase

### Marketing money is wasted on the wrong users

### The company wants to predict purchase probability

### The data science team has been asked to build a machine learning system that predicts whether a customer will purchase a product during a session.

### If the system predicts high probability of purchase, the system will:

### show personalized product recommendations

### offer targeted discounts

### prioritize marketing campaigns

### If the system predicts low probability, the company will avoid spending marketing resources.

### However, the dataset contains both numerical and categorical features, so the data science team must design a complete ML pipeline.

### Business Objective
### Build a machine learning model that predicts whether a user will purchase (1) or not purchase (0) during a website session.

### The model must be implemented using scikit-learn pipelines, including:

### Encoding techniques

### Feature preprocessing

### Model training

### Model selection

### Hyperparameter tuning

In [142]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score,r2_score, classification_report

In [157]:
df=pd.read_excel('DatasetCapstoneProject3.xlsx')

In [158]:
df.head()

,CustomerID,Age,Gender,Device,Traffic_Source,Time_on_Website,Pages_Visited,Ad_Clicks,Previous_Purchases,Purchased
0,1,23,Male,Mobile,Social Media,5,3,1,0,0
1,2,35,Female,Desktop,Search Engine,12,8,3,2,1
2,3,29,Male,Tablet,Social Media,8,5,2,1,0
3,4,41,Female,Mobile,Email Campaign,15,10,4,3,1
4,5,22,Female,Desktop,Direct,4,2,0,0,0

In [159]:
df.columns = df.columns.str.strip()

In [171]:
df["Gender"] = df["Gender"].map({
    "Male":1,
    "Female":0
})

In [172]:
X=df.drop(['CustomerID','Purchased'],axis=1)

In [175]:
X.head()

,Age,Gender,Device,Traffic_Source,Time_on_Website,Pages_Visited,Ad_Clicks,Previous_Purchases
0,23,1,Mobile,Social Media,5,3,1,0
1,35,0,Desktop,Search Engine,12,8,3,2
2,29,1,Tablet,Social Media,8,5,2,1
3,41,0,Mobile,Email Campaign,15,10,4,3
4,22,0,Desktop,Direct,4,2,0,0

In [176]:
y=df['Purchased']

In [177]:
y.head()

0    0
1    1
2    0
3    1
4    0
Name: Purchased, dtype: int64

In [178]:
# Automatically dividing the data in numerical and categorical data by using select_dtypes method

In [179]:
numerical_cols = X.select_dtypes(include=["int64","float64"]).columns

categorical_cols = X.select_dtypes(include=["object"]).columns

In [184]:
print("Numerical:", numerical_cols)
print("Categorical:", categorical_cols)

Numerical: Index(['Age', 'Gender', 'Time_on_Website', 'Pages_Visited', 'Ad_Clicks',
       'Previous_Purchases'],
      dtype='object')
Categorical: Index(['Device', 'Traffic_Source'], dtype='object')

In [ ]:
# applying scaler operation on columns using ColumnTransformer library

In [186]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_cols),
        ("cat", OneHotEncoder(), categorical_cols)
    ]
)

In [ ]:
# using complete ML pipeline

In [187]:
model = Pipeline([
    ("preprocessing", preprocessor),
    ("classifier", LogisticRegression())
])

In [ ]:
# splitting the data in training as testing parts

In [188]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [189]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['Age', 'Gender', 'Time_on_Website', 'Pages_Visited', 'Ad_Clicks',
       'Previous_Purchases'],
      dtype='object')),
                                                 ('cat', OneHotEncoder(),
                                                  Index(['Device', 'Traffic_Source'], dtype='object'))])),
                ('classifier', LogisticRegression())])

In [ ]:
# prdicting the value either customer will buy or not

In [191]:
y_pred = model.predict(X_test)

In [192]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         1

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

In [196]:
new_customer = pd.DataFrame({
    "Age":[30],
    "Gender":["1"],
    "Device":["Mobile"],
    "Traffic_Source":["Social Media"],
    "Time_on_Website":[7],
    "Pages_Visited":[5],
    "Ad_Clicks":[2],
    "Previous_Purchases":[1]
})

prediction = model.predict(new_customer)
probability = model.predict_proba(new_customer)

if prediction==0:
    print('Customer will not purchase')
else:
    print('Customer will purchase')

print("Prediction:", prediction)
print("Purchase Probability:", probability)

Customer will not purchase
Prediction: [0]
Purchase Probability: [[0.79678553 0.20321447]]