In [ ]:
Description
Capstone Project: Student Success & Career Path Prediction

Scenario

The university wants to analyze student performance data to:

Predict exam scores (Regression).
Classify students into “At Risk” vs. “On Track” categories (Classification).
Cluster students into groups with similar study habits (Clustering).
Recommend interventions (extra tutoring, workshops, counseling).

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.cluster import KMeans
from sklearn.metrics import mean_absolute_error, r2_score, classification_report, silhouette_score

In [3]:
df=pd.read_csv("Student_Success_Career_Path.csv")

In [4]:
df.head()

,Student_ID,Hours_Studied,Attendance (%),Assignments_Submitted,Previous_Sem_GPA,Participation_Score,Final_Exam_Score,Pass_Fail,Career_Readiness_Score,Age,Gender
0,S001,10,85,8,3.2,70,78,Pass,65,20,Female
1,S002,5,60,5,2.5,55,55,Fail,40,21,Male
2,S003,12,90,9,3.8,80,88,Pass,75,22,Female
3,S004,3,40,3,2.0,45,45,Fail,35,19,Male
4,S005,8,75,7,3.0,65,70,Pass,60,23,Female

In [5]:
df_model = df.copy()

df_model = df_model.drop("Student_ID", axis=1)

df_model["Gender"] = df_model["Gender"].map({"Male": 0, "Female": 1})

In [6]:
df_model

,Hours_Studied,Attendance (%),Assignments_Submitted,Previous_Sem_GPA,Participation_Score,Final_Exam_Score,Pass_Fail,Career_Readiness_Score,Age,Gender
0,10,85,8,3.2,70,78,Pass,65,20,1
1,5,60,5,2.5,55,55,Fail,40,21,0
2,12,90,9,3.8,80,88,Pass,75,22,1
3,3,40,3,2.0,45,45,Fail,35,19,0
4,8,75,7,3.0,65,70,Pass,60,23,1
5,6,65,6,2.7,60,60,Pass,55,20,0
6,2,30,2,1.8,40,40,Fail,25,21,1
7,11,88,9,3.5,75,82,Pass,70,22,0
8,4,50,4,2.2,50,50,Fail,45,19,1
9,9,80,8,3.1,68,75,Pass,62,20,0
10,7,72,6,2.9,63,68,Pass,58,21,1
11,1,25,1,1.5,35,35,Fail,20,19,0
12,13,92,10,3.9,85,90,Pass,80,22,1
13,6,60,5,2.6,58,58,Pass,50,20,0
14,4,45,3,2.1,48,48,Fail,38,21,1
15,10,87,8,3.4,72,80,Pass,68,23,0
16,5,55,4,2.3,52,52,Fail,42,19,1
17,12,91,9,3.7,78,85,Pass,72,22,0
18,3,35,2,1.9,42,42,Fail,30,20,1
19,9,82,8,3.2,70,77,Pass,64,21,0

In [ ]:
# Regression

In [7]:
X_reg = df_model.drop(["Final_Exam_Score", "Pass_Fail"], axis=1)
y_reg = df_model["Final_Exam_Score"]

X_train, X_test, y_train, y_test = train_test_split(
    X_reg, y_reg, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

reg_model = LinearRegression()
reg_model.fit(X_train_scaled, y_train)

pred = reg_model.predict(X_test_scaled)

print("Regression Results")
print("MAE:", mean_absolute_error(y_test, pred))
print("R2 Score:", r2_score(y_test, pred))

Regression Results
MAE: 2.001246947798693
R2 Score: 0.9455693142315345

In [8]:
X_reg

,Hours_Studied,Attendance (%),Assignments_Submitted,Previous_Sem_GPA,Participation_Score,Career_Readiness_Score,Age,Gender
0,10,85,8,3.2,70,65,20,1
1,5,60,5,2.5,55,40,21,0
2,12,90,9,3.8,80,75,22,1
3,3,40,3,2.0,45,35,19,0
4,8,75,7,3.0,65,60,23,1
5,6,65,6,2.7,60,55,20,0
6,2,30,2,1.8,40,25,21,1
7,11,88,9,3.5,75,70,22,0
8,4,50,4,2.2,50,45,19,1
9,9,80,8,3.1,68,62,20,0
10,7,72,6,2.9,63,58,21,1
11,1,25,1,1.5,35,20,19,0
12,13,92,10,3.9,85,80,22,1
13,6,60,5,2.6,58,50,20,0
14,4,45,3,2.1,48,38,21,1
15,10,87,8,3.4,72,68,23,0
16,5,55,4,2.3,52,42,19,1
17,12,91,9,3.7,78,72,22,0
18,3,35,2,1.9,42,30,20,1
19,9,82,8,3.2,70,64,21,0

In [ ]:
# Classification

In [9]:
df_model["Pass_Fail"] = df_model["Pass_Fail"].map({"Fail": 0, "Pass": 1})

X_clf = df_model.drop("Pass_Fail", axis=1)
y_clf = df_model["Pass_Fail"]

X_train, X_test, y_train, y_test = train_test_split(
    X_clf, y_clf, test_size=0.2, random_state=42
)

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

clf_model = LogisticRegression(max_iter=1000)
clf_model.fit(X_train_scaled, y_train)

pred = clf_model.predict(X_test_scaled)

print("\nClassification Results")
print(classification_report(y_test, pred))

Classification Results
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.75      1.00      0.86         3

    accuracy                           0.75         4
   macro avg       0.38      0.50      0.43         4
weighted avg       0.56      0.75      0.64         4

C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [10]:
df_model['Pass_Fail']

0     1
1     0
2     1
3     0
4     1
5     1
6     0
7     1
8     0
9     1
10    1
11    0
12    1
13    1
14    0
15    1
16    0
17    1
18    0
19    1
Name: Pass_Fail, dtype: int64

In [ ]:
# Clustering

In [11]:
features = df_model[
    ["Hours_Studied",
     "Attendance (%)",
     "Assignments_Submitted",
     "Participation_Score"]
]

X_scaled = scaler.fit_transform(features)

kmeans = KMeans(n_clusters=3, random_state=42)
df_model["Cluster"] = kmeans.fit_predict(X_scaled)

print("\nSilhouette Score:", silhouette_score(X_scaled, df_model["Cluster"]))

print("\nCluster Means:")
print(df_model.groupby("Cluster").mean())

C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

Silhouette Score: 0.5333654802395095

Cluster Means:
         Hours_Studied  Attendance (%)  Assignments_Submitted  \
Cluster
0            10.750000          86.875                  8.625
1             2.833333          37.500                  2.500
2             6.166667          64.500                  5.500

         Previous_Sem_GPA  Participation_Score  Final_Exam_Score  Pass_Fail  \
Cluster
0                3.475000            74.750000         81.875000   1.000000
1                1.916667            43.333333         43.333333   0.000000
2                2.666667            58.833333         60.500000   0.666667

         Career_Readiness_Score        Age    Gender
Cluster
0                     69.500000  21.500000  0.375000
1                     32.166667  19.833333  0.666667
2                     50.833333  20.666667  0.500000

In [12]:
features

    Hours_Studied  Attendance (%)  Assignments_Submitted  Participation_Score
0              10              85                      8                   70
1               5              60                      5                   55
2              12              90                      9                   80
3               3              40                      3                   45
4               8              75                      7                   65
5               6              65                      6                   60
6               2              30                      2                   40
7              11              88                      9                   75
8               4              50                      4                   50
9               9              80                      8                   68
10              7              72                      6                   63
11              1              25                      1                   35
12             13              92                     10                   85
13              6              60                      5                   58
14              4              45                      3                   48
15             10              87                      8                   72
16              5              55                      4                   52
17             12              91                      9                   78
18              3              35                      2                   42
19              9              82                      8                   70