In [4]:
import numpy as np
a=np.array([12,43,5,3,2,33,56,89])
a

array([12, 43,  5,  3,  2, 33, 56, 89])

In [14]:
matrix=np.array([[1,2,3],[4,5,6]])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.shape(matrix)

(2, 3)

In [12]:
## Data Explopration

In [4]:
import pandas as pd
df=pd.read_csv("sample_data1 - Sheet1.csv")
df.head()
df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         15 non-null     int64
 1   Department          15 non-null     object
 2   Region              15 non-null     object
 3   Salary              15 non-null     int64
 4   Experience_Years    15 non-null     int64
 5   Performance_Rating  14 non-null     float64
 6   Monthly_Sales       14 non-null     float64
dtypes: float64(2), int64(3), object(2)
memory usage: 972.0+ bytes

,Employee_ID,Salary,Experience_Years,Performance_Rating,Monthly_Sales
count,15.000000,15.000000,15.000000,14.000000,14.000000
mean,1008.000000,49666.666667,3.200000,3.785714,76928.571429
std,4.472136,7158.079019,1.373213,0.892582,62039.025293
min,1001.000000,39000.000000,1.000000,2.000000,0.000000
25%,1004.500000,45500.000000,2.000000,3.000000,0.000000
50%,1008.000000,49000.000000,3.000000,4.000000,95000.000000
75%,1011.500000,52500.000000,4.000000,4.000000,128750.000000
max,1015.000000,62000.000000,6.000000,5.000000,150000.000000

In [5]:
emp=pd.read_csv("employee_attrition - Sheet1.csv")
emp.info()
emp.shape
print(f"Missing values\n{emp.isnull().sum()}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Employee_ID       15 non-null     object
 1   Age               15 non-null     int64
 2   Department        15 non-null     object
 3   Job_Role          15 non-null     object
 4   Monthly_Income    15 non-null     int64
 5   Years_at_Company  15 non-null     int64
 6   Overtime          15 non-null     object
 7   Job_Satisfaction  14 non-null     float64
 8   Attrition         15 non-null     object
dtypes: float64(1), int64(3), object(5)
memory usage: 1.2+ KB
Missing values
Employee_ID         0
Age                 0
Department          0
Job_Role            0
Monthly_Income      0
Years_at_Company    0
Overtime            0
Job_Satisfaction    1
Attrition           0
dtype: int64

In [6]:
emp.head()

,Employee_ID,Age,Department,Job_Role,Monthly_Income,Years_at_Company,Overtime,Job_Satisfaction,Attrition
0,E001,29,Sales,Sales Executive,45000,3,Yes,4.0,No
1,E002,35,HR,HR Manager,52000,7,No,3.0,No
2,E003,28,IT,Software Engineer,60000,2,Yes,2.0,Yes
3,E004,42,Finance,Accountant,58000,10,No,4.0,No
4,E005,31,Sales,Sales Executive,47000,4,Yes,3.0,Yes

In [7]:
emp["Monthly_Income"].mean()

56533.333333333336

In [8]:
emp["Department"].max()

'Sales'

In [1]:
import numpy as np
np.random.normal().round(1)

AttributeError: 'float' object has no attribute 'round'