In [1]:
# Question 2

In [3]:
import numpy as np
import pandas as pd

sales=pd.read_csv("Sales1 - Sheet1.csv")
sales.head()

  OrderID CustomerID Product  Quantity  Price   OrderDate
0   O1001       C001  Laptop         2  55000  2023-04-10
1   O1002       C002  Mobile         1  25000  2023-04-12
2   O1003       C003  Tablet         3  15000  2023-05-01
3   O1004       C004  Laptop         1  60000  2023-05-15
4   O1005       C005  Mobile         2  22000  2023-06-05

In [5]:
count=sales.isnull().sum()
print("Null Values: ",count)

Null Values:  OrderID       0
CustomerID    0
Product       0
Quantity      0
Price         0
OrderDate     0
dtype: int64

In [6]:
count1=sales.notnull().sum()
print("Total Values: ",count1)

Total Values:  OrderID       8
CustomerID    8
Product       8
Quantity      8
Price         8
OrderDate     8
dtype: int64

In [9]:
print("Mean Price: ",sales["Price"].mean())

Mean Price:  31875.0

In [10]:
print("Max Price: ",sales["Price"].max())

Max Price:  60000

In [11]:
print("Min Price: ",sales["Price"].min())

Min Price:  2000

In [12]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     8 non-null      object
 1   CustomerID  8 non-null      object
 2   Product     8 non-null      object
 3   Quantity    8 non-null      int64
 4   Price       8 non-null      int64
 5   OrderDate   8 non-null      object
dtypes: int64(2), object(4)
memory usage: 516.0+ bytes

In [13]:
sales.describe()

       Quantity         Price
count  8.000000      8.000000
mean   2.125000  31875.000000
std    1.356203  22433.632277
min    1.000000   2000.000000
25%    1.000000  17250.000000
50%    2.000000  23500.000000
75%    2.250000  55750.000000
max    5.000000  60000.000000